packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@sentry/cli': false
  esbuild: true
  msw: true
  react-native-nitro-modules: true
  sharp: true
  unrs-resolver: true
minimumReleaseAge: 1440
