import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadPlannerContractFixtures } from "../src/lib/planner/contracts/load-fixtures";

const outputPath = path.resolve(
  process.cwd(),
  "supabase/tests/generated/planner_contracts.generated.test.sql"
);
const checkOnly = process.argv.includes("--check");

function canonicalize(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalize);
  }

  if (value !== null && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, entry]) => [key, canonicalize(entry)])
    );
  }

  return value;
}

function sqlJson(value: unknown) {
  const json = JSON.stringify(canonicalize(value));
  const delimiter = "$planner_fixture$";

  if (json.includes(delimiter)) {
    throw new Error(`Fixture JSON contains reserved SQL delimiter ${delimiter}.`);
  }

  return `${delimiter}${json}${delimiter}::jsonb`;
}

function generateSql() {
  const fixtures = [...loadPlannerContractFixtures()].sort((left, right) =>
    left.contract.localeCompare(right.contract)
  );
  const assertionCount = fixtures.length * 3;
  const lines = [
    "-- Generated by scripts/generate-planner-sql-fixtures.ts. Do not edit.",
    "-- The canonical source is test/fixtures/planner-contracts/*.v1.json.",
    "",
    "begin;",
    "create extension if not exists pgtap with schema extensions;",
    "set local search_path = public, extensions, pg_catalog;",
    `select plan(${assertionCount});`,
    "",
    "create temporary table planner_contract_cases (",
    "  contract text not null,",
    "  schema_version text not null,",
    "  case_id text not null,",
    "  payload jsonb not null,",
    "  primary key (contract, case_id)",
    ") on commit drop;",
    "",
  ];

  for (const fixture of fixtures) {
    const sortedCases = [...fixture.cases].sort((left, right) =>
      left.id.localeCompare(right.id)
    );

    for (const fixtureCase of sortedCases) {
      lines.push(
        "insert into planner_contract_cases (contract, schema_version, case_id, payload)",
        `values ('${fixture.contract}', '${fixture.schemaVersion}', '${fixtureCase.id}', ${sqlJson(
          fixtureCase
        )});`
      );
    }

    lines.push(
      "",
      "select is(",
      `  (select count(*) from planner_contract_cases where contract = '${fixture.contract}'),`,
      `  ${sortedCases.length}::bigint,`,
      `  '${fixture.contract} generated case count matches canonical JSON'`,
      ");",
      "select is(",
      `  (select count(distinct case_id) from planner_contract_cases where contract = '${fixture.contract}'),`,
      `  ${sortedCases.length}::bigint,`,
      `  '${fixture.contract} generated case ids are unique'`,
      ");",
      "select ok(",
      "  not exists (",
      "    select 1",
      "    from planner_contract_cases",
      `    where contract = '${fixture.contract}'`,
      "      and (schema_version <> '1' or jsonb_typeof(payload) <> 'object')",
      "  ),",
      `  '${fixture.contract} generated payloads retain schema version and object shape'`,
      ");",
      ""
    );
  }

  lines.push("select * from finish();", "rollback;", "");
  return lines.join("\n");
}

async function main() {
  const generated = generateSql();

  if (!checkOnly) {
    await writeFile(outputPath, generated, "utf8");
    console.log(`Generated ${path.relative(process.cwd(), outputPath)}.`);
    return;
  }

  let current: string;
  try {
    current = await readFile(outputPath, "utf8");
  } catch {
    throw new Error(
      `Missing ${path.relative(
        process.cwd(),
        outputPath
      )}; run pnpm contracts:generate-sql.`
    );
  }

  if (current !== generated) {
    throw new Error(
      "Generated planner SQL fixtures are stale; run pnpm contracts:generate-sql."
    );
  }

  console.log("Generated planner SQL fixtures are current.");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
